# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=128, verbose_name=b'\xe5\xb7\xa5\xe5\x85\xb7\xe5\x90\x8d')),
                ('toolpath', models.CharField(max_length=128, verbose_name=b'\xe5\xb7\xa5\xe5\x85\xb7\xe5\x9c\xb0\xe5\x9d\x80')),
                ('toolclass', models.CharField(choices=[(b'windows', b'windows'), (b'linux', b'linux'), (b'mac', b'mac')], max_length=30, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab')),
                ('toolcapacity', models.FloatField(blank=True, null=True, verbose_name=b'\xe5\xb7\xa5\xe5\x85\xb7(\xe5\x8d\x95\xe4\xbd\x8dGb)')),
                ('recordtime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u5de5\u5177\u4fe1\u606f',
                'verbose_name_plural': '\u5de5\u5177\u4fe1\u606f',
            },
        ),
    ]
