# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, null=True, verbose_name=b'ip')),
                ('filesystem', models.CharField(max_length=64, verbose_name=b'filesystem')),
                ('size', models.CharField(max_length=64, verbose_name=b'size')),
                ('used', models.CharField(max_length=64, verbose_name=b'used')),
                ('avail', models.CharField(max_length=64, verbose_name=b'avail')),
                ('use', models.CharField(max_length=64, verbose_name=b'Use%')),
                ('mounted', models.TextField(max_length=64, verbose_name=b'mounted')),
                ('createtime', models.DateTimeField(verbose_name='\u4fdd\u5b58\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u78c1\u76d8\u5bb9\u91cf\u6570\u636e',
                'verbose_name_plural': '\u78c1\u76d8\u5bb9\u91cf\u6570\u636e',
            },
        ),
    ]
